package com.StudentMgmt.SMS_Backend.service;

import com.StudentMgmt.SMS_Backend.dto.StudentDto;
import java.util.List;

public interface StudentService {

    // Create a new student (id will be auto-generated by DB)
    StudentDto createStudent(StudentDto studentDto);

    // Get a student by ID
    StudentDto getStudentById(Long studentId);

    // Get all students
    List<StudentDto> getAllStudents();

    // Update student by ID
    StudentDto updateStudent(Long studentId, StudentDto studentDto);

    // Delete student by ID
    void deleteStudent(Long studentId);
}
